name: Run integration test

on: [push, pull_request]

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: v0.9.0

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init


      - name: Run TFLint
        run: tflint -f compact